### ISSUE TITLE
New Win Build?

### ISSUE THREAD

**Issue by zvezdochiot** [ksharindam/photoquick#7]
Subj.

Current: https://github.com/ksharindam/photoquick/releases/download/v4.2.4/PhotoQuick4.2.4.exe

**Comment by ksharindam** [comment]
I thought to upload a windows package, when i did last commit.
But forgot that.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

I would have done it myself. But I have some kind of nonsense going on with libraries. In addition, you pack in one exe.

**Comment by ksharindam** [comment]
I was busy last few days. So did not get time.
Tomorrow I shall upload the package myself.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

https://github.com/ksharindam/photoquick/releases/tag/v4.3.7 : 

https://github.com/ksharindam/photoquick/releases/download/v4.3.7/PhotoQuick.4.3.7.exe

Not found QtCored4.dll , QtGuid4.dll ! Not used QtCore4.dll , QtGui4.dll !

**Comment by ksharindam** [comment]
I have installed it. And it has been installed without error. And also running without any problem.
May be you are doing something wrong.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

```sh
strings photoquick.exe
```
```log
...
9_ZThn8_NK7QWidget9releaseDCEP5HDC__
libgcc_s_dw2-1.dll
KERNEL32.dll
msvcrt.dll
libgomp-1.dll
libstdc++-6.dll
QtCored4.dll
QtGuid4.dll
```
take a look yourself.

**Comment by ksharindam** [comment]
Try the 4.2.4 release package, and tell if it has same problem.

**Comment by zvezdochiot** [comment]
@ksharindam say:
>Try the 4.2.4 release package, and tell if it has same problem.

Not. 4.2.4 used QtCore4.dll , QtGui4.dll .

**Comment by ksharindam** [comment]
You are right.
Mine was working because it gets required libraries from the Installed Qt
4.8.7

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

I tried to compile the current photoquick with QtCore4.dll, QtGui4.dll (handles). Compiles, but plugins stop loading.

**Comment by ksharindam** [comment]
I had to add
CONFIG -= debug
to link against non-debug libraries.
Otherwise it links against debug version of libraries.

**Comment by zvezdochiot** [comment]
@ksharindam say:
>CONFIG -= debug

It doesn't work for me (but this is not an indicator!).

```sh
strings photoquick.exe
```
```log
9_ZThn8_NK7QWidget9releaseDCEP5HDC__
libgcc_s_dw2-1.dll
KERNEL32.dll
msvcrt.dll
libgomp-1.dll
libstdc++-6.dll
QtCored4.dll
QtGuid4.dll
```

**Comment by zvezdochiot** [comment]
@ksharindam say:
>https://github.com/ksharindam/photoquick/releases/tag/v4.3.7

```sh

```

```log
&4_ZThn8_NK7QWidget9releaseDCEP5HDC__
libgcc_s_dw2-1.dll
KERNEL32.dll
msvcrt.dll
libgomp-1.dll
libstdc++-6.dll
QtCore4.dll
QtGui4.dll
```
❓ Plugins?

**Comment by ksharindam** [comment]
We have to add
CONFIG -= debug
line in all of the .pro files.
This will solve the problem of plugins.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

I clone https://github.com/ksharindam/photoquick and build. Option https://github.com/ksharindam/photoquick/issues/7#issuecomment-753638891 work.

```sh
strings photoquick.exe
```
```log
&4_ZThn8_NK7QWidget9releaseDCEP5HDC__
libgcc_s_dw2-1.dll
KERNEL32.dll
msvcrt.dll
libgomp-1.dll
libstdc++-6.dll
QtCore4.dll
QtGui4.dll
```
Looks like I'm over it again somewhere.

**Comment by zvezdochiot** [comment]
https://github.com/ksharindam/photoquick/releases/tag/v4.3.7

**Comment by ksharindam** [comment]
@zvezdochiot so it works now?

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

The photoquick itself works great. Will plugins work? This takes time.

**Comment by ksharindam** [comment]
I hope it will work.
But make sure you have that

CONFIG -= debug_and_release debug

Line in the .pro files (kuwahara.pro, invert.pro etc) of photoquick-plugins
project

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

All works. See https://github.com/ImageProcessing-ElectronicPublications/photoquick/releases/download/4.3.7/PhotoQuick-4.3.7-plugins-win32.zip
