### ISSUE TITLE
FPNG?

### ISSUE THREAD

**Issue by zvezdochiot** [ksharindam/photoquick#8]
Hi @ksharindam .

:question: Maybe use FPNG (https://github.com/richgel999/fpng) for fast write?

**Comment by ksharindam** [comment]
This should be done by creating a qt imageformat plugin

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Maybe use?:
```cpp
QImageWriter iw;
iw.setCompression(1);
iw.write(image);
```

**Comment by zvezdochiot** [comment]
overdue
